"""Generate a detailed code map for backend/app.

Outputs:
- docs/code_map_detailed.md : detailed per-file function list with signatures, docstrings, and usages
- docs/code_map.dot : graphviz DOT file showing module-level edges (imports and cross-file calls)

Usage:
    python backend\scripts\generate_code_map.py

This script is conservative (uses simple text searches for usages) but provides a useful starting point.
"""
from __future__ import annotations
import ast
import os
import re
from pathlib import Path
from typing import Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[2]  # repo root (d:/ai-support-agent)
# Scan the whole repository (exclude virtualenvs and git internals)
APP_DIR = ROOT
DOCS_DIR = ROOT / 'docs'
DOCS_DIR.mkdir(parents=True, exist_ok=True)

def _is_excluded(p: Path) -> bool:
    parts = [str(x).lower() for x in p.parts]
    if any(pn in parts for pn in ('.venv', 'venv', '.git', '__pycache__')):
        return True
    return False

PY_FILES: List[Path] = [p for p in ROOT.rglob('*.py') if not _is_excluded(p)]

# Data structures
FileFuncs: Dict[str, List[Dict]] = {}
ModuleImports: Dict[str, List[str]] = {}

# Helper: read file

def read_text(p: Path) -> str:
    # Try utf-8-sig to gracefully handle BOM (U+FEFF) then fallback
    for enc in ('utf-8-sig', 'utf-8', 'latin-1'):
        try:
            return p.read_text(encoding=enc)
        except Exception:
            continue
    # Last resort
    return p.read_text(errors='replace')

# Extract functions via AST
for p in PY_FILES:
    try:
        rel = p.relative_to(ROOT)  # path from repo root
    except Exception:
        rel = p
    key = str(rel)
    src = read_text(p)
    try:
        tree = ast.parse(src)
    except Exception as e:
        print(f"AST parse failed for {p}: {e}")
        continue
    funcs = []
    imports = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            try:
                if isinstance(node, ast.Import):
                    for n in node.names:
                        imports.append(n.name)
                else:
                    mod = node.module if node.module else ''
                    if node.level and node.level > 0:
                        mod = '.' * node.level + mod
                    imports.append(mod)
            except Exception:
                pass
        if isinstance(node, ast.FunctionDef):
            name = node.name
            lineno = node.lineno
            # build signature string
            args = []
            for a in node.args.args:
                args.append(a.arg)
            if node.args.vararg:
                args.append('*' + node.args.vararg.arg)
            if node.args.kwarg:
                args.append('**' + node.args.kwarg.arg)
            sig = f"({', '.join(args)})"
            doc = ast.get_docstring(node) or ''
            funcs.append({'name': name, 'lineno': lineno, 'sig': sig, 'doc': doc})
    FileFuncs[key] = funcs
    ModuleImports[key] = imports

# Simple usage search: for each function name, search across files for occurrences of "name(" or ".name(" or " name (" (with whitespace)
AllFilesText: Dict[str, str] = {str(p.relative_to(ROOT)): read_text(p) for p in PY_FILES}

Usages: Dict[Tuple[str, str], List[Tuple[str, int, str]]] = {}
# key: (file, func_name) -> list of (using_file, line_no, line_text)
# Use a fast substring search instead of heavy regex to improve performance
for file, funcs in FileFuncs.items():
    for f in funcs:
        fname = f['name']
        fname_call = fname + '('
        hits: List[Tuple[str, int, str]] = []
        for ufile, text in AllFilesText.items():
            # quick skip
            if fname not in text:
                continue
            for i, line in enumerate(text.splitlines(), start=1):
                if fname_call in line:
                    # ignore the function definition in the same file at same line
                    if ufile == file and i == f['lineno']:
                        continue
                    # avoid matching 'def fname(' by checking prefix
                    if line.lstrip().startswith('def ' + fname + '('):
                        continue
                    hits.append((ufile, i, line.strip()))
        Usages[(file, fname)] = hits

# Build module-level edges: if file A references function from file B, add edge A->B
Edges: Dict[str, Dict[str, int]] = {}
for (file, fname), hits in Usages.items():
    for ufile, _, _ in hits:
        src = ufile
        dst = file
        if src == dst:
            continue
        Edges.setdefault(src, {})
        Edges[src][dst] = Edges[src].get(dst, 0) + 1

# Write detailed markdown
md_lines = ["# Detailed Code Map\n", "Generated by backend/scripts/generate_code_map.py\n\n"]
md_lines.append("## Files and functions (detailed)\n")
for file in sorted(FileFuncs.keys()):
    md_lines.append(f"### {file}\n")
    funcs = FileFuncs[file]
    if not funcs:
        md_lines.append("(no top-level functions)\n\n")
        continue
    for f in funcs:
        md_lines.append(f"- **{f['name']} {f['sig']}** (line {f['lineno']})\n")
        doc = f['doc'].strip() if f['doc'] else ''
        if doc:
            md_lines.append(f"  - Doc: {doc.splitlines()[0]}\n")
        else:
            md_lines.append("  - Doc: *none*\n")
        uses = Usages.get((file, f['name']), [])
        if uses:
            md_lines.append(f"  - Used in {len(uses)} locations:\n")
            for ufile, lineno, line in uses[:50]:
                md_lines.append(f"    - `{ufile}`:{lineno} — `{line}`\n")
            if len(uses) > 50:
                md_lines.append(f"    - ... (+{len(uses)-50} more)\n")
        else:
            md_lines.append("  - Used in: *(no matches found)*\n")
    md_lines.append("\n")

# write to docs
out_md = DOCS_DIR / 'code_map_full.md'
out_md.write_text('\n'.join(md_lines), encoding='utf-8')
print(f'Wrote {out_md}')

# write DOT graph
dot_lines = ['digraph code_map {', '  rankdir=LR;', '  node [shape=box,fontname="Courier"];']
# create nodes for files (short names)
for f in sorted(FileFuncs.keys()):
    name = f.replace('/', '__').replace('.', '_')
    label = f
    dot_lines.append(f'  "{name}" [label="{label}"];')
# edges
for src, targets in Edges.items():
    src_name = src.replace('/', '__').replace('.', '_')
    for dst, count in targets.items():
        dst_name = dst.replace('/', '__').replace('.', '_')
        dot_lines.append(f'  "{src_name}" -> "{dst_name}" [label="{count}"];')

dot_lines.append('}')
out_dot = DOCS_DIR / 'code_map_full.dot'
out_dot.write_text('\n'.join(dot_lines), encoding='utf-8')
print(f'Wrote {out_dot}')

# Done
print('Generation complete. Outputs: docs/code_map_detailed.md, docs/code_map.dot')
