"""
Intelligence Pipeline Endpoints
Exposes the NLP ticket analysis, cluster queries, and knowledge graph statistics.
Prefix: /api/v1/intelligence
"""
from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
import json
from pathlib import Path

router = APIRouter()

OUTPUT_DIR = Path(__file__).parents[6] / "data_pipeline" / "output"


# ─────────────────────────────────────────────
# Schemas
# ─────────────────────────────────────────────

class TicketAnalysisRequest(BaseModel):
    text: str = Field(..., min_length=5, description="Raw ticket text to analyze")
    app_id: str = Field(default="BRASIL", description="Application context")
    ticket_id: Optional[str] = Field(default=None, description="Optional ticket identifier")


class TicketAnalysisResponse(BaseModel):
    ticket_id: str
    language: str
    intent: str
    application: str
    related_systems: List[str]
    incident_type: str
    error_codes: List[str]
    entities: List[Dict[str, Any]]
    confidence: float
    trust_score: float
    action_requested: str
    requires_human_review: bool


class ClusterSummary(BaseModel):
    cluster_id: str
    name: str
    size: int
    incident_type: str
    top_error_codes: List[str]
    trust_score: float
    keywords: List[str]


class GraphStats(BaseModel):
    total_nodes: int
    total_edges: int
    node_types: Dict[str, int]
    edge_types: Dict[str, int]
    top_applications: List[str]
    top_incident_types: List[str]


# ─────────────────────────────────────────────
# Endpoints
# ─────────────────────────────────────────────

@router.post("/analyze-ticket", response_model=TicketAnalysisResponse, tags=["intelligence"])
async def analyze_ticket(request: TicketAnalysisRequest):
    """
    Analyze a raw ticket text using the NLP enrichment pipeline.

    Returns:
    - Detected intent (investigate_error, delete_equipment, etc.)
    - Incident type from BRASIL taxonomy (25+ types)
    - Extracted entities (equipment_id, error_code, user_id, etc.)
    - Trust score and confidence
    - Whether human review is recommended
    """
    try:
        from app.services.nlp.enricher import ticket_enricher

        structured = ticket_enricher.enrich(
            raw_text=request.text,
            ticket_id=request.ticket_id or "api_request",
            fallback_application=request.app_id,
        )
        return TicketAnalysisResponse(
            ticket_id=structured.ticket_id,
            language=structured.language,
            intent=structured.intent,
            application=structured.application,
            related_systems=structured.related_systems,
            incident_type=structured.incident_type,
            error_codes=structured.error_codes,
            entities=[{"type": e.entity_type, "value": e.value, "confidence": e.confidence}
                      for e in structured.entities],
            confidence=structured.confidence,
            trust_score=structured.trust_score,
            action_requested=structured.action_requested,
            requires_human_review=structured.requires_human_review,
        )
    except ImportError:
        raise HTTPException(status_code=503, detail="NLP enrichment service not available")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/clusters", response_model=List[ClusterSummary], tags=["intelligence"])
async def list_clusters(
    min_size: int = Query(default=3, ge=1, description="Minimum cluster size to return"),
    incident_type: Optional[str] = Query(default=None, description="Filter by incident type"),
    limit: int = Query(default=50, le=200),
):
    """
    List all ticket clusters generated by the HDBSCAN clustering step.

    Requires: `data_pipeline/run_pipeline.py --step cluster` to have been run.
    """
    cluster_file = OUTPUT_DIR / "cluster_results.json"
    if not cluster_file.exists():
        raise HTTPException(
            status_code=404,
            detail="cluster_results.json not found. Run: python data_pipeline/run_pipeline.py --step cluster"
        )
    try:
        data = json.loads(cluster_file.read_text(encoding="utf-8"))
        clusters = data.get("clusters", [])

        # Filter
        if incident_type:
            clusters = [c for c in clusters if c.get("incident_type") == incident_type]
        clusters = [c for c in clusters if c.get("size", 0) >= min_size]

        # Sort by size desc
        clusters.sort(key=lambda c: c.get("size", 0), reverse=True)
        clusters = clusters[:limit]

        return [
            ClusterSummary(
                cluster_id=c.get("cluster_id", ""),
                name=c.get("name", ""),
                size=c.get("size", 0),
                incident_type=c.get("incident_type", ""),
                top_error_codes=c.get("top_error_codes", [])[:5],
                trust_score=c.get("trust_score", 0.0),
                keywords=c.get("keywords", [])[:8],
            )
            for c in clusters
        ]
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/graph", response_model=GraphStats, tags=["intelligence"])
async def get_graph_stats():
    """
    Get knowledge graph statistics: node/edge counts by type, top applications and incident types.

    Requires: `data_pipeline/run_pipeline.py --step graph` to have been run.
    """
    graph_file = OUTPUT_DIR / "knowledge_graph.json"
    if not graph_file.exists():
        raise HTTPException(
            status_code=404,
            detail="knowledge_graph.json not found. Run: python data_pipeline/run_pipeline.py --step graph"
        )
    try:
        data = json.loads(graph_file.read_text(encoding="utf-8"))
        nodes = data.get("nodes", {})
        edges = data.get("edges", [])

        # Count node types
        node_type_counts: Dict[str, int] = {}
        for node in nodes.values():
            nt = node.get("node_type", "unknown")
            node_type_counts[nt] = node_type_counts.get(nt, 0) + 1

        # Count edge types
        edge_type_counts: Dict[str, int] = {}
        for edge in edges:
            et = edge.get("edge_type", "unknown")
            edge_type_counts[et] = edge_type_counts.get(et, 0) + 1

        # Top applications (node_type == Application)
        apps = [
            n.get("id", "")
            for n in nodes.values()
            if n.get("node_type") == "Application"
        ]

        # Top incident types (node_type == IncidentType)
        inc_types = [
            n.get("id", "")
            for n in nodes.values()
            if n.get("node_type") == "IncidentType"
        ]

        return GraphStats(
            total_nodes=len(nodes),
            total_edges=len(edges),
            node_types=node_type_counts,
            edge_types=edge_type_counts,
            top_applications=sorted(apps)[:10],
            top_incident_types=sorted(inc_types)[:15],
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/taxonomy", tags=["intelligence"])
async def get_incident_taxonomy():
    """
    Return the full BRASIL incident taxonomy (25+ types across 8 categories).
    Useful for frontend filtering and display.
    """
    try:
        from app.services.nlp.taxonomy import INCIDENT_TAXONOMY
        return {
            inc_id: {
                "category": inc.category,
                "name": inc.name,
                "description": inc.description,
                "related_systems": inc.related_systems,
                "severity": inc.severity,
            }
            for inc_id, inc in INCIDENT_TAXONOMY.items()
        }
    except ImportError:
        raise HTTPException(status_code=503, detail="NLP taxonomy service not available")


@router.get("/pipeline-status", tags=["intelligence"])
async def get_pipeline_status():
    """
    Returns the status of each knowledge pipeline artifact (which steps have been run).
    """
    artifacts = [
        ("fr_parsed.json",            "1. FR Parser"),
        ("fr_scored.json",            "2. FR Quality Scorer"),
        ("ticket_analysis.json",      "3. Ticket Analyzer"),
        ("canonical_candidates.json", "4. Canonical Builder"),
        ("ticket_structured.json",    "6. Ticket Structurer (NLP)"),
        ("fr_normalized.json",        "7. FR Normalizer"),
        ("cluster_results.json",      "8. Clustering Engine"),
        ("knowledge_graph.json",      "9. Knowledge Graph Builder"),
    ]
    status = {}
    for filename, label in artifacts:
        path = OUTPUT_DIR / filename
        if path.exists():
            size_kb = path.stat().st_size // 1024
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
                if isinstance(data, list):
                    count = len(data)
                elif isinstance(data, dict):
                    count = len(data.get("clusters") or data.get("nodes") or data)
                else:
                    count = 0
            except Exception:
                count = -1
            status[label] = {"exists": True, "size_kb": size_kb, "items": count}
        else:
            status[label] = {"exists": False, "size_kb": 0, "items": 0}
    return {"pipeline_dir": str(OUTPUT_DIR), "artifacts": status}
