"""
db_query_registry.py
━━━━━━━━━━━━━━━━━━━━
Central whitelist registry of ALL allowed read-only SQL queries.

SECURITY RULES:
  - NO raw SQL from user
  - NO SQL generated by LLM
  - ONLY queries defined here are executable
  - All queries are SELECT only (enforced by db_service)
  - Parameters are positional and validated

Each entry:
  sql      : parameterized SELECT statement (%s placeholders)
  params   : ordered list of parameter names (for documentation & validation)
  timeout  : per-query timeout in seconds (overrides default)
  max_rows : hard row limit (overrides default)
  tags     : list of intent/entity tags for diagnostic_planner routing
"""

from typing import Any, Dict

# ─────────────────────────────────────────────────────────────────────────────
# Query registry
# ─────────────────────────────────────────────────────────────────────────────

ALLOWED_QUERIES: Dict[str, Dict[str, Any]] = {

    # ── Equipment ────────────────────────────────────────────────────────────

    "get_equipment_id": {
        "sql": (
            # Real schema: t_equipments — eqpt_name VARCHAR(20), eqpt_state VARCHAR(1),
            # eqpt_prodstate VARCHAR(1), eqpt_runtimetype DECIMAL(1), node_id
            # States: A=Actif F=Fermé P=EnCours S=Suppression C=Créé
            "SELECT eqpt_id, eqpt_name, eqpt_state, eqpt_prodstate, eqpt_runtimetype, node_id "
            "FROM t_equipments "
            "WHERE UPPER(eqpt_name) = UPPER(%s) "
            "   OR UPPER(eqpt_name) LIKE UPPER('%%' || %s || '%%') "
            "LIMIT 5"
        ),
        "params": ["equipment_name", "equipment_name"],
        "timeout": 5,
        "max_rows": 5,
        "tags": ["equipment", "delete_equipment", "check_equipment"],
    },

    "get_equipment_by_id": {
        "sql": (
            "SELECT eqpt_id, eqpt_name, eqpt_state, eqpt_prodstate, eqpt_runtimetype, "
            "       eqpt_ipadress, node_id, lgem_id "
            "FROM t_equipments "
            "WHERE eqpt_id = %s "
            "LIMIT 1"
        ),
        "params": ["eqpt_id"],
        "timeout": 5,
        "max_rows": 1,
        "tags": ["equipment"],
    },

    "check_equipment_status": {
        "sql": (
            # eqpt_state VARCHAR(1): A=Actif F=Fermé P=EnCours S=Suppression C=Créé
            # eqpt_prodstate VARCHAR(1): production state
            "SELECT eqpt_id, eqpt_name, eqpt_state, eqpt_prodstate, eqpt_runtimetype, node_id "
            "FROM t_equipments "
            "WHERE UPPER(eqpt_name) = UPPER(%s)"
        ),
        "params": ["equipment_name"],
        "timeout": 5,
        "max_rows": 1,
        "tags": ["equipment", "delete_equipment"],
    },

    # ── Residual data checks ──────────────────────────────────────────────────

    "check_residual_references": {
        "sql": (
            # Real schema: residual checks against real tables
            "SELECT 't_shelfs' AS src, COUNT(*) AS cnt "
            "FROM t_shelfs WHERE eqpt_id = %s "
            "UNION ALL "
            "SELECT 't_service_access_mrts', COUNT(*) "
            "FROM t_service_access_mrts WHERE eqpt_id = %s "
            "UNION ALL "
            "SELECT 't_mrt_access_dslams', COUNT(*) "
            "FROM t_mrt_access_dslams WHERE a_eqpt_id = %s "
            "UNION ALL "
            "SELECT 't_res_prod_controlables', COUNT(*) "
            "FROM t_res_prod_controlables WHERE a_eqpt_id = %s "
        ),
        "params": ["eqpt_id", "eqpt_id", "eqpt_id", "eqpt_id"],
        "timeout": 10,
        "max_rows": 20,
        "tags": ["delete_equipment", "residual_data"],
    },

    "check_active_services": {
        "sql": (
            # Real schema: t_service_access_mrts links MRT SAM to equipment
            # samv_currentstate VARCHAR(1): D=Désactivé S=Supprimé, others=active
            "SELECT sam.sram_id, sam.sram_circuitid, sam.mrty_id, "
            "       samv.samv_currentstate, samv.samv_versno "
            "FROM t_service_access_mrts sam "
            "LEFT JOIN t_service_access_mrt_vers samv ON sam.sram_id = samv.sram_id "
            "WHERE sam.eqpt_id = %s "
            "  AND (samv.samv_currentstate IS NULL OR samv.samv_currentstate NOT IN ('S','D')) "
            "LIMIT 20"
        ),
        "params": ["eqpt_id"],
        "timeout": 8,
        "max_rows": 20,
        "tags": ["delete_equipment", "active_services"],
    },

    "check_mrt_dslam_links": {
        "sql": (
            # Real schema: t_medialinks (not t_media_links), mdlk_state SMALLINT
            "SELECT mdlk_id, mdlk_state, mdlk_runtimetype, a_eqpt_id, b_eqpt_id, "
            "       a_node_id, b_node_id "
            "FROM t_medialinks "
            "WHERE (a_eqpt_id = %s OR b_eqpt_id = %s) "
            "AND mdlk_state != 2 "
            "LIMIT 30"
        ),
        "params": ["eqpt_id", "eqpt_id"],
        "timeout": 10,
        "max_rows": 30,
        "tags": ["delete_equipment", "links"],
    },

    "check_cards_on_equipment": {
        "sql": (
            # Real schema: t_cards.shlf_id → t_shelfs.eqpt_id
            # card_type VARCHAR(1), card_prodstate text, card_cardno SMALLINT
            "SELECT c.card_id, c.card_cardno, c.card_type, c.card_prodstate, c.cmod_id "
            "FROM t_cards c "
            "JOIN t_shelfs s ON c.shlf_id = s.shlf_id "
            "WHERE s.eqpt_id = %s "
            "LIMIT 50"
        ),
        "params": ["eqpt_id"],
        "timeout": 8,
        "max_rows": 50,
        "tags": ["delete_equipment", "cards"],
    },

    # ── VLAN ─────────────────────────────────────────────────────────────────

    "get_vlan_by_id": {
        "sql": (
            # Real schema: VLANs are in t_res_prod_controlables (type V)
            # rpct_cclname = VLAN CCL name, rpct_vlaninterne = internal VLAN id (VARCHAR 5)
            "SELECT rpct_id, rpct_type, rpct_cclname, rpct_prodstate, rpct_vlaninterne, "
            "       a_eqpt_id, b_eqpt_id, role_id "
            "FROM t_res_prod_controlables "
            "WHERE rpct_id = %s "
            "LIMIT 1"
        ),
        "params": ["vlan_id"],
        "timeout": 5,
        "max_rows": 1,
        "tags": ["vlan", "delete_vlan"],
    },

    "check_vlan_residual_resources": {
        "sql": (
            # Check resource usages and roles linked to a VLAN (resprodcontrolable)
            "SELECT 't_res_prod_roles' AS src, COUNT(*) AS cnt "
            "FROM t_res_prod_roles WHERE rpct_id = %s "
            "UNION ALL "
            "SELECT 't_resourceusages', COUNT(*) "
            "FROM t_resourceusages WHERE rpct_id = %s "
            "UNION ALL "
            "SELECT 't_netresrels', COUNT(*) "
            "FROM t_netresrels WHERE rpct_id = %s"
        ),
        "params": ["vlan_id", "vlan_id", "vlan_id"],
        "params": ["vlan_id", "vlan_id"],
        "timeout": 10,
        "max_rows": 10,
        "tags": ["vlan", "delete_vlan", "residual_data"],
    },

    # ── VC / VP counters ──────────────────────────────────────────────────────

    "check_vc_counters": {
        "sql": (
            # Real schema: t_d_rscvcis (VC states), linked via t_res_prod_controlables
            "SELECT v.rscv_id, v.rscv_state, v.rpct_id, "
            "       r.a_eqpt_id, r.rpct_cclname "
            "FROM t_d_rscvcis v "
            "JOIN t_res_prod_controlables r ON v.rpct_id = r.rpct_id "
            "WHERE r.a_eqpt_id = %s AND v.rscv_state = 'O' "
            "LIMIT 30"
        ),
        "params": ["eqpt_id"],
        "timeout": 8,
        "max_rows": 30,
        "tags": ["vc", "counters", "affectation"],
    },

    "check_resource_counters": {
        "sql": (
            # Real schema: t_res_prod_controlables — rpct_allocatedvccount, rpct_prodstate, rpct_vcmax
            "SELECT rpct_id, rpct_type, rpct_prodstate, rpct_allocatedvccount, "
            "       rpct_vcmax, rpct_vcmin, rpct_cclname, rpct_vlaninterne "
            "FROM t_res_prod_controlables "
            "WHERE a_eqpt_id = %s "
            "LIMIT 50"
        ),
        "params": ["eqpt_id"],
        "timeout": 8,
        "max_rows": 50,
        "tags": ["counters", "resources"],
    },

    # ── ND (Noeud de Distribution — 9-digit subscriber number) ──────────────

    "get_nd_by_number": {
        "sql": (
            # ND info is NOT in a t_nd table — it's stored in t_tpinitialstates.tpis_nd
            # and t_mrt_access_dslams.dsam_nd and t_makingfiles.mkfl_nd (all VARCHAR 15)
            # This query looks up TP plans involving this ND number
            "SELECT tis.tpis_id, tis.tpis_nd, tis.tp_id, "
            "       tp.tp_dslamn, tp.tp_dslamn1, tp.tp_state, tp.tp_creationdate "
            "FROM t_tpinitialstates tis "
            "JOIN t_tps tp ON tis.tp_id = tp.tp_id "
            "WHERE tis.tpis_nd = %s "
            "ORDER BY tp.tp_creationdate DESC "
            "LIMIT 5"
        ),
        "params": ["nd_number"],
        "timeout": 5,
        "max_rows": 5,
        "tags": ["nd", "error_1300", "check_nd"],
    },

    "check_nd_tp_status": {
        "sql": (
            # Real schema: t_tpinitialstates.tpis_nd VARCHAR(15), t_tps.tp_state SMALLINT
            # tp_state: 1=EnCours, 2=Exécuté, 3=Erreur; tp_dslamn = nom DSLAM source
            "SELECT tis.tpis_id, tis.tp_id, tis.tpis_nd, "
            "       tp.tp_dslamn, tp.tp_dslamn1, tp.tp_state, tp.tp_creationdate, "
            "       tp.tp_executiondate "
            "FROM t_tpinitialstates tis "
            "JOIN t_tps tp ON tis.tp_id = tp.tp_id "
            "WHERE tis.tpis_nd = %s "
            "ORDER BY tp.tp_creationdate DESC "
            "LIMIT 10"
        ),
        "params": ["nd_number"],
        "timeout": 8,
        "max_rows": 10,
        "tags": ["nd", "error_1300", "tp", "check_nd"],
    },

    "check_nd_services": {
        "sql": (
            # t_mrt_access_dslams.dsam_nd contains the ND number
            # This shows MRT DSLAM accesses linked to this ND
            "SELECT dsam.dsam_id, dsam.dsam_customerid, dsam.dsam_nd, dsam.dsam_crcmrtid, "
            "       dsmv.dsmv_currentstate, dsmv.dsmv_versno "
            "FROM t_mrt_access_dslams dsam "
            "LEFT JOIN t_mrt_access_dslam_vers dsmv ON dsam.dsam_id = dsmv.dsam_id "
            "WHERE dsam.dsam_nd = %s "
            "ORDER BY dsmv.dsmv_versno DESC "
            "LIMIT 20"
        ),
        "params": ["nd_number"],
        "timeout": 8,
        "max_rows": 20,
        "tags": ["nd", "services", "check_nd"],
    },

    "check_tps_by_nd_1300": {
        "sql": (
            # Real schema: tp_state SMALLINT (1=EnCours/bloqué, 3=Erreur), tpis_nd VARCHAR(15)
            "SELECT tp.tp_id, tp.tp_dslamn, tp.tp_dslamn1, tp.tp_state, "
            "       tp.tp_creationdate, tp.tp_executiondate, tp.tp_comments "
            "FROM t_tps tp "
            "JOIN t_tpinitialstates tis ON tp.tp_id = tis.tp_id "
            "WHERE tis.tpis_nd = %s "
            "  AND tp.tp_state IN (1, 3) "
            "ORDER BY tp.tp_creationdate DESC "
            "LIMIT 10"
        ),
        "params": ["nd_number"],
        "timeout": 10,
        "max_rows": 10,
        "tags": ["nd", "error_1300", "tp", "blocked_tp"],
    },

    # ── Node / Répartiteur ────────────────────────────────────────────────────

    "get_node_by_name": {
        "sql": (
            # Real schema: node_name42c VARCHAR(20), node_internationalname VARCHAR(19)
            # node_basecode42c VARCHAR(6), node_functioncode VARCHAR(4)
            "SELECT node_id, node_name42c, node_nodecode, node_basecode42c, "
            "       node_internationalname, node_functioncode, node_localareashortname, site_id "
            "FROM t_nodes "
            "WHERE UPPER(node_name42c) = UPPER(%s) "
            "   OR UPPER(node_internationalname) = UPPER(%s) "
            "LIMIT 5"
        ),
        "params": ["node_name", "node_name"],
        "timeout": 5,
        "max_rows": 5,
        "tags": ["node", "node_absent"],
    },

    "check_node_equipment_link": {
        "sql": (
            "SELECT eqpt_id, eqpt_name, eqpt_state, eqpt_prodstate, eqpt_runtimetype, node_id "
            "FROM t_equipments "
            "WHERE node_id = %s "
            "LIMIT 30"
        ),
        "params": ["node_id"],
        "timeout": 5,
        "max_rows": 30,
        "tags": ["node", "equipment"],
    },

    # ── TP (Transfer Plan) ────────────────────────────────────────────────────

    "get_blocked_tps": {
        "sql": (
            # Real schema: tp_dslamn VARCHAR(20), tp_state SMALLINT
            # tp_state 1=EnCours (bloqué), tp_creationdate INTEGER
            "SELECT tp_id, tp_dslamn, tp_dslamn1, tp_state, tp_creationdate, tp_executiondate "
            "FROM t_tps "
            "WHERE tp_dslamn = %s AND tp_state = 1 "
            "ORDER BY tp_creationdate DESC "
            "LIMIT 10"
        ),
        "params": ["dslam_name"],
        "timeout": 8,
        "max_rows": 10,
        "tags": ["tp", "blocked_tp"],
    },

    "get_tp_initial_states": {
        "sql": (
            # Real schema: t_tpinitialstates — tpis_id, tpis_nd VARCHAR(15)
            # tpis_vpinitial, tpis_vcinitial = VP/VC initial values
            "SELECT tpis_id, tp_id, tpis_nd, tpis_vpinitial, tpis_vcinitial, "
            "       tpis_vpcible, tpis_vccible, tpis_isnewvp "
            "FROM t_tpinitialstates "
            "WHERE tp_id = %s "
            "LIMIT 50"
        ),
        "params": ["tp_id"],
        "timeout": 8,
        "max_rows": 50,
        "tags": ["tp"],
    },

    # ── Port / Broche ─────────────────────────────────────────────────────────

    "check_port_attribution": {
        "sql": (
            # Real schema: port_portno SMALLINT, port_outstate VARCHAR(1),
            # port_occupstate SMALLINT, port_prodstate VARCHAR(1)
            "SELECT port_id, port_portno, port_outstate, port_occupstate, "
            "       port_prodstate, port_occupont, card_id "
            "FROM t_ports "
            "WHERE card_id = %s "
            "ORDER BY port_portno ASC "
            "LIMIT 100"
        ),
        "params": ["card_id"],
        "timeout": 8,
        "max_rows": 100,
        "tags": ["port", "broche", "affectation"],
    },

    "check_shared_port_links": {
        "sql": (
            # Real table: t_medialinks (not t_media_links)
            "SELECT b_port_id, COUNT(*) AS link_count "
            "FROM t_medialinks "
            "WHERE b_eqpt_id = %s AND b_port_id IS NOT NULL "
            "GROUP BY b_port_id "
            "HAVING COUNT(*) > 1 "
            "LIMIT 20"
        ),
        "params": ["eqpt_id"],
        "timeout": 10,
        "max_rows": 20,
        "tags": ["port", "shared_port", "link"],
    },

    # ── Operator ──────────────────────────────────────────────────────────────

    "check_operator_mrt_links": {
        "sql": (
            # Real schema: t_mrt_access_dslams.oper_id FK → t_operators.oper_id
            "SELECT COUNT(*) AS mrt_count "
            "FROM t_mrt_access_dslams "
            "WHERE oper_id = %s"
        ),
        "params": ["operator_id"],
        "timeout": 8,
        "max_rows": 1,
        "tags": ["operator", "delete_operator"],
    },

    # ── t_ports.t_remarks anomaly ─────────────────────────────────────────────

    "check_port_remarks_anomaly": {
        "sql": (
            # Real schema: t_ports.port_remarks VARCHAR(60), t_cards.card_cardno SMALLINT
            "SELECT e.eqpt_name, c.card_cardno, p.port_portno, LEFT(p.port_remarks, 100) AS remarks_preview "
            "FROM t_cards c "
            "JOIN t_shelfs s ON c.shlf_id = s.shlf_id "
            "JOIN t_equipments e ON s.eqpt_id = e.eqpt_id "
            "JOIN t_ports p ON c.card_id = p.card_id "
            "WHERE p.port_remarks IS NOT NULL "
            "AND p.port_remarks !~ '^[\\x00-\\x7E\\xE0-\\xEF\\xB0\\xF4\\xC9\\xFB]*$' "
            "LIMIT 20"
        ),
        "params": [],
        "timeout": 15,
        "max_rows": 20,
        "tags": ["port", "remarks", "anomaly", "charset"],
    },

    # ── Erreur 1300 (TP bloqués en état 1300) ────────────────────────────────

    "check_error_1300_tps": {
        "sql": (
            # Real schema: tp_state SMALLINT, tp_dslamn VARCHAR(20), tp_creationdate INTEGER
            # tp_state 1=EnCours/bloqué, 3=Erreur
            "SELECT tp_id, tp_dslamn, tp_dslamn1, tp_state, tp_creationdate, "
            "       tp_executiondate, tp_delayed, tp_comments "
            "FROM t_tps "
            "WHERE tp_state IN (1, 3) "
            "ORDER BY tp_creationdate DESC "
            "LIMIT 20"
        ),
        "params": [],
        "timeout": 10,
        "max_rows": 20,
        "tags": ["error_1300", "tp", "blocked_tp"],
    },

    "check_tps_by_dslam_1300": {
        "sql": (
            # Real schema: tp_dslamn VARCHAR(20), tp_state SMALLINT (1=EnCours, 3=Erreur)
            "SELECT tp_id, tp_dslamn, tp_dslamn1, tp_state, tp_creationdate, "
            "       tp_executiondate, tp_comments "
            "FROM t_tps "
            "WHERE UPPER(tp_dslamn) LIKE UPPER('%%' || %s || '%%') "
            "  AND tp_state IN (1, 3) "
            "ORDER BY tp_creationdate DESC "
            "LIMIT 20"
        ),
        "params": ["dslam_name"],
        "timeout": 10,
        "max_rows": 20,
        "tags": ["error_1300", "tp", "blocked_tp"],
    },

    # ── IHM bloquée (DSM PARAM / script bloqué) ───────────────────────────────

    "check_ihm_locked_equipment": {
        "sql": (
            # eqpt_state VARCHAR(1): A=Actif F=Fermé P=EnCours S=Suppression C=Créé
            # P=en cours de modification (IHM locked), C=en cours de création
            "SELECT eqpt_id, eqpt_name, eqpt_state, eqpt_prodstate, node_id "
            "FROM t_equipments "
            "WHERE eqpt_state IN ('P', 'C') "
            "LIMIT 30"
        ),
        "params": [],
        "timeout": 8,
        "max_rows": 30,
        "tags": ["fix_ihm_blocked", "locked"],
    },

    "check_ihm_blocked_scripts": {
        "sql": (
            # Real schema: t_es (External Scripts) with t_estypes
            # es_state: 1=running, 2=error, 3=warning, 4=completed
            "SELECT es.es_id, es.es_state, es.es_equipment, es.es_user, es.es_code, "
            "       es.es_requestdate, est.est_name, est.est_scriptdir "
            "FROM t_es es "
            "JOIN t_estypes est ON es.est_id = est.est_id "
            "WHERE es.es_state IN (1, 2, 3) "
            "ORDER BY es.es_requestdate DESC "
            "LIMIT 20"
        ),
        "params": [],
        "timeout": 8,
        "max_rows": 20,
        "tags": ["fix_ihm_blocked", "script"],
    },

    # ── DLM recovery ─────────────────────────────────────────────────────────

    "check_blocked_dlm": {
        "sql": (
            # DLM operations tracked via t_es (External Script) + t_estypes
            # t_dlm doesn't exist in schema — use t_es with DLM-type operations
            "SELECT es.es_id, es.es_state, es.es_equipment, es.es_user, "
            "       es.es_code, es.es_requestdate, est.est_name "
            "FROM t_es es "
            "JOIN t_estypes est ON es.est_id = est.est_id "
            "WHERE es.es_state IN (2, 3) "
            "  AND UPPER(est.est_name) LIKE '%%DLM%%' "
            "ORDER BY es.es_requestdate DESC "
            "LIMIT 30"
        ),
        "params": [],
        "timeout": 10,
        "max_rows": 30,
        "tags": ["dlm", "blocked_dlm"],
    },

    # ── BAS / Router deletion ─────────────────────────────────────────────────

    "check_bas_residual_data": {
        "sql": (
            # Real schema: no t_services/t_vlans/t_mrtdslam — use actual tables
            "SELECT 't_service_access_mrts' AS src, COUNT(*) AS cnt FROM t_service_access_mrts WHERE eqpt_id = %s "
            "UNION ALL "
            "SELECT 't_mrt_access_dslams', COUNT(*) FROM t_mrt_access_dslams WHERE a_eqpt_id = %s "
            "UNION ALL "
            "SELECT 't_res_prod_controlables', COUNT(*) FROM t_res_prod_controlables WHERE a_eqpt_id = %s"
        ),
        "params": ["eqpt_id", "eqpt_id", "eqpt_id"],
        "timeout": 10,
        "max_rows": 10,
        "tags": ["bas", "router", "delete_bas", "residual_data"],
    },

    # ── MakingFile / Dossier de réalisation ──────────────────────────────────

    "get_making_file_by_nd": {
        "sql": (
            # t_makingfiles: mkfl_nd VARCHAR(15), mkfl_state SMALLINT
            # States: 0=CREATED 1=ALLOCATED 2=IN_PROGRESS 3=PARTLY_CONFIGURED 4=CONFIGURED 5=AVP
            "SELECT mkfl_id, mkfl_fileid, mkfl_customername, mkfl_customerid, "
            "       mkfl_nd, mkfl_state, mkfl_farid, mkfl_businessprocess, "
            "       mkfl_currentcrcid, mkfl_basecode42c "
            "FROM t_makingfiles "
            "WHERE mkfl_nd = %s "
            "ORDER BY mkfl_creationdate_time DESC "
            "LIMIT 10"
        ),
        "params": ["nd_number"],
        "timeout": 8,
        "max_rows": 10,
        "tags": ["nd", "making_file", "dossier"],
    },

    "get_making_file_by_fileid": {
        "sql": (
            "SELECT mkfl_id, mkfl_fileid, mkfl_customername, mkfl_customerid, "
            "       mkfl_nd, mkfl_state, mkfl_farid, mkfl_businessprocess, "
            "       mkfl_currentcrcid, mkfl_previouscrcid, mkfl_basecode42c, "
            "       mkfl_creationdate_time, mkfl_lastconfigphase "
            "FROM t_makingfiles "
            "WHERE mkfl_fileid = %s "
            "LIMIT 1"
        ),
        "params": ["file_id"],
        "timeout": 5,
        "max_rows": 1,
        "tags": ["making_file", "dossier", "ftth", "cl"],
    },

    "check_mrt_access_by_equipment": {
        "sql": (
            # t_mrt_access_dslams: dsam_nd, dsam_crcmrtid (CRC MRT ID), dsam_customerid
            # dsmv_currentstate VARCHAR(1): A=Actif D=Désactivé S=Supprimé
            "SELECT dsam.dsam_id, dsam.dsam_customerid, dsam.dsam_nd, dsam.dsam_crcmrtid, "
            "       dsam.dsam_farid, dsmv.dsmv_currentstate, dsmv.dsmv_versno "
            "FROM t_mrt_access_dslams dsam "
            "LEFT JOIN t_mrt_access_dslam_vers dsmv ON dsam.dsam_id = dsmv.dsam_id "
            "WHERE dsam.a_eqpt_id = %s "
            "  AND (dsmv.dsmv_currentstate IS NULL OR dsmv.dsmv_currentstate NOT IN ('D','S')) "
            "ORDER BY dsmv.dsmv_versno DESC "
            "LIMIT 20"
        ),
        "params": ["eqpt_id"],
        "timeout": 10,
        "max_rows": 20,
        "tags": ["equipment", "mrt", "dslam"],
    },

    "get_epcvers_by_making_file": {
        "sql": (
            # t_epcvers: epcv_currentstate VARCHAR(1) linked via t_epcversimpacts.mkfl_id
            "SELECT ev.epcv_id, ev.epcv_versno, ev.epcv_currentstate, "
            "       ev.epcv_lastmodifydate, ev.dsam_id, ev.epc_id "
            "FROM t_epcvers ev "
            "JOIN t_epcversimpacts evi ON ev.evim_id = evi.evim_id "
            "WHERE evi.mkfl_id = %s "
            "ORDER BY ev.epcv_versno DESC "
            "LIMIT 20"
        ),
        "params": ["mkfl_id"],
        "timeout": 8,
        "max_rows": 20,
        "tags": ["epc", "umiepc", "making_file"],
    },

    "get_es_logs_by_equipment": {
        "sql": (
            # t_es: es_state 1=running 2=error 3=warning 4=completed
            # es_equipment = equipment name, t_eslogs has log content
            "SELECT es.es_id, es.es_state, es.es_equipment, es.es_code, "
            "       es.es_requestdate, est.est_name, "
            "       el.esl_filename, LEFT(el.esl_logfile, 500) AS log_preview "
            "FROM t_es es "
            "JOIN t_estypes est ON es.est_id = est.est_id "
            "LEFT JOIN t_eslogs el ON es.es_id = el.es_id "
            "WHERE UPPER(es.es_equipment) = UPPER(%s) "
            "ORDER BY es.es_requestdate DESC "
            "LIMIT 10"
        ),
        "params": ["equipment_name"],
        "timeout": 10,
        "max_rows": 10,
        "tags": ["equipment", "logs", "es"],
    },
}

# ─────────────────────────────────────────────────────────────────────────────
# Intent -> queries routing table (used by diagnostic_planner)
# ─────────────────────────────────────────────────────────────────────────────

INTENT_QUERY_PLAN: Dict[str, list] = {
    "delete_equipment": [
        "get_equipment_id",
        "check_residual_references",
        "check_active_services",
        "check_mrt_dslam_links",
        "check_cards_on_equipment",
    ],
    "delete_vlan": [
        "get_vlan_by_id",
        "check_vlan_residual_resources",
    ],
    "delete_operator": [
        "check_operator_mrt_links",
    ],
    "delete_bas": [
        "get_equipment_id",
        "check_bas_residual_data",
    ],
    "fix_vc_counters": [
        "get_equipment_id",
        "check_vc_counters",
        "check_resource_counters",
    ],
    "fix_port_assignment": [
        "check_port_attribution",
        "check_shared_port_links",
    ],
    "fix_blocked_tp": [
        "get_blocked_tps",
        "get_tp_initial_states",
    ],
    "check_node": [
        "get_node_by_name",
        "check_node_equipment_link",
    ],
    "fix_port_remarks": [
        "check_port_remarks_anomaly",
    ],
    "fix_blocked_dlm": [
        "check_blocked_dlm",
    ],
    # order_blocked: generic "suppression/commande impossible" — run full equipment investigation
    "order_blocked": [
        "get_equipment_id",
        "check_equipment_status",
        "check_residual_references",
        "check_active_services",
        "check_mrt_dslam_links",
        "check_cards_on_equipment",
    ],
    # R4 — error_1300: TPs bloqués en état 1300 (FR 130)
    "error_1300": [
        "check_error_1300_tps",
        "get_blocked_tps",
    ],
    # error_1300 pour un ND (9 chiffres) — priorité ND
    "error_1300_nd": [
        "get_nd_by_number",
        "check_nd_tp_status",
        "check_tps_by_nd_1300",
        "check_nd_services",
    ],
    # check_nd: requêtes générales ND
    "check_nd": [
        "get_nd_by_number",
        "check_nd_tp_status",
        "check_nd_services",
    ],
    # R4 — fix_ihm_blocked: IHM bloquée / script en cours / DSM PARAM (FR 182, FR 163, FR 164)
    "fix_ihm_blocked": [
        "check_ihm_locked_equipment",
        "check_ihm_blocked_scripts",
    ],
    # R4 — fix_vc_counters_dslam: compteurs VC/VP/VLAN DSLAM (FR 135, FR 136c)
    "fix_vc_counters_dslam": [
        "get_equipment_id",
        "check_vc_counters",
        "check_resource_counters",
    ],
    # check_making_file: dossier de réalisation par ND ou par file_id
    "check_making_file": [
        "get_making_file_by_nd",
        "get_epcvers_by_making_file",
    ],
    # check_mrt_equipment: MRT access analysis for an equipment
    "check_mrt_equipment": [
        "get_equipment_id",
        "check_mrt_access_by_equipment",
        "check_active_services",
    ],
    # check_es_logs: External Script (ES) log analysis
    "check_es_logs": [
        "get_es_logs_by_equipment",
        "check_blocked_dlm",
    ],
}


def get_query(name: str) -> Dict[str, Any] | None:
    """Return a query definition by name, or None if not whitelisted."""
    return ALLOWED_QUERIES.get(name)


def get_plan_for_intent(intent: str) -> list:
    """Return the ordered list of query names for a given intent."""
    return INTENT_QUERY_PLAN.get(intent, [])


def list_all_queries() -> list:
    return list(ALLOWED_QUERIES.keys())
